# Generated by Django 5.0 on 2023-12-17 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default='2023-01-01')),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default='100', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default='2023-01-01')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('complaints', models.TextField()),
                ('diagnosis', models.TextField()),
                ('prescriptions', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.patient')),
                ('veterinarian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.veterinarian')),
            ],
        ),
        migrations.CreateModel(
            name='ProvidedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2023-01-01')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.service')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.visit')),
            ],
        ),
    ]
