# Generated by Django 5.0 on 2023-12-18 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Владелец', 'verbose_name_plural': 'Владельцы'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.AlterModelOptions(
            name='providedservice',
            options={'verbose_name': 'Оказанные услуги', 'verbose_name_plural': 'Оказанные услуги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='veterinarian',
            options={'verbose_name': 'Ветеринар', 'verbose_name_plural': 'Ветеринары'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_of_birth',
            field=models.DateField(default='2023-01-01', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='animal_type',
            field=models.CharField(max_length=30, verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(default='2023-01-01', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.owner', verbose_name='Владалец'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='date',
            field=models.DateField(default='2023-01-01', verbose_name='Дата оказания услуги'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='providedservice',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.visit', verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='veterinarian',
            name='position',
            field=models.CharField(max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='complaints',
            field=models.TextField(verbose_name='Жалобы'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.patient', verbose_name='id пациента'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prescriptions',
            field=models.TextField(verbose_name='Предписания'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='veterinarian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals.veterinarian', verbose_name='Принимающий врач'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(verbose_name='Дата посещения'),
        ),
    ]
