# Generated by Django 5.0 on 2023-12-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_visit_complaints_remove_visit_diagnosis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anamnesis',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='anamnesis',
            old_name='visit_id',
            new_name='visit',
        ),
    ]
