# Generated by Django 5.0 on 2023-12-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_rename_patient_id_anamnesis_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone',
        ),
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.CharField(default=112, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='password_ow',
            field=models.CharField(default=123, max_length=20, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='username',
            field=models.CharField(default=1234, max_length=20, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
