# Generated by Django 5.0 on 2024-01-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_remove_owner_address_remove_owner_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='animals.service', verbose_name='id услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_time',
            field=models.CharField(default=1, verbose_name='Время посещения'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProvidedService',
        ),
    ]
